type bst = Leaf | Node of bst * int * bst

let insert _ _ = failwith "TODO"
let contains _ _ = failwith "TODO"
let get_max _ = failwith "TODO"
let delete _ _ = failwith "TODO"
let height _ = failwith "TODO"
let inorder _ = failwith "TODO"
let preorder _ = failwith "TODO"
let postorder _ = failwith "TODO"
let mirror _ = failwith "TODO"
let length _ = failwith "TODO"
let sum _ = failwith "TODO"
let prod _ = failwith "TODO"
let map _ _ = failwith "TODO"
let fold_left _ _ _ = failwith "TODO"
let filter _ _ = failwith "TODO"
let partition _ _ = failwith "TODO"
